export {
  getDepositStats,
  getDepositStatsForTeam,
  setTeamTarget,
  getTeamTargets,
  getMyTeamTarget,
  setAgentTarget,
  getAgentsTargetsSummary,
  getMyDeposits,
  getMyTarget,
  getMyEarnings,
  createDeposit,
  deleteDeposit,
  getDepositsHistory,
  getMonthReport,
} from "./deposits.api";
